with open("C:/xampp/htdocs/agri_forecast/agri_mobile/lib/main.dart", "r", encoding="utf-8", newline="") as f:
    content = f.read()

ai_widget = (
    "// =============================================================\r\n"
    "//  AI ASSISTANT SHEET\r\n"
    "// =============================================================\r\n"
    "class _AiAssistantSheet extends StatefulWidget {\r\n"
    "  const _AiAssistantSheet();\r\n"
    "  @override\r\n"
    "  State<_AiAssistantSheet> createState() => _AiAssistantSheetState();\r\n"
    "}\r\n"
    "\r\n"
    "class _AiAssistantSheetState extends State<_AiAssistantSheet> {\r\n"
    "  final _ctrl = TextEditingController();\r\n"
    "  bool _loading = false;\r\n"
    "  String? _answer;\r\n"
    "  String? _error;\r\n"
    "\r\n"
    "  Future<void> _ask() async {\r\n"
    "    final q = _ctrl.text.trim();\r\n"
    "    if (q.isEmpty) return;\r\n"
    "    setState(() { _loading = true; _answer = null; _error = null; });\r\n"
    "    try {\r\n"
    "      final d = await ApiService.post('/ask', {\r\n"
    "        'question': q,\r\n"
    "        'farm_size_acres': UserSession.farmSizeAcres,\r\n"
    "        'sector': UserSession.sector,\r\n"
    "        'lang': T.rw ? 'rw' : 'en',\r\n"
    "      }, requireAuth: false);\r\n"
    "      if (d['status'] == 'success') {\r\n"
    "        setState(() => _answer = d['answer'] as String);\r\n"
    "      } else {\r\n"
    "        setState(() => _error = d['message'] ?? 'Failed');\r\n"
    "      }\r\n"
    "    } catch (e) {\r\n"
    "      setState(() => _error = e.toString());\r\n"
    "    }\r\n"
    "    if (mounted) setState(() => _loading = false);\r\n"
    "  }\r\n"
    "\r\n"
    "  @override\r\n"
    "  Widget build(BuildContext context) {\r\n"
    "    return Container(\r\n"
    "      decoration: const BoxDecoration(\r\n"
    "        color: Colors.white,\r\n"
    "        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),\r\n"
    "      ),\r\n"
    "      padding: EdgeInsets.fromLTRB(20, 12, 20,\r\n"
    "          MediaQuery.of(context).viewInsets.bottom + 28),\r\n"
    "      child: SingleChildScrollView(\r\n"
    "        child: Column(\r\n"
    "          mainAxisSize: MainAxisSize.min,\r\n"
    "          crossAxisAlignment: CrossAxisAlignment.start,\r\n"
    "          children: [\r\n"
    "            Center(\r\n"
    "              child: Container(width: 40, height: 4,\r\n"
    "                decoration: BoxDecoration(color: kBorder,\r\n"
    "                    borderRadius: BorderRadius.circular(2))),\r\n"
    "            ),\r\n"
    "            const SizedBox(height: 16),\r\n"
    "            Row(children: [\r\n"
    "              const Icon(Icons.smart_toy, color: kForest, size: 26),\r\n"
    "              const SizedBox(width: 10),\r\n"
    "              Text(\r\n"
    "                T.rw ? 'Umufasha wa AI' : 'AI Farm Assistant',\r\n"
    "                style: const TextStyle(fontSize: 17,\r\n"
    "                    fontWeight: FontWeight.w800, color: kForest),\r\n"
    "              ),\r\n"
    "            ]),\r\n"
    "            const SizedBox(height: 6),\r\n"
    "            Text(\r\n"
    "              T.rw\r\n"
    "                  ? 'Baza ikibazo icyo aricyo cyose ku bijyanye no gutera - gisubiza hakoreshejwe amakuru y\\'isoko yo muri Musanze'\r\n"
    "                  : 'Ask any farming question - answers use live Musanze market data',\r\n"
    "              style: const TextStyle(fontSize: 12, color: kMuted),\r\n"
    "            ),\r\n"
    "            const SizedBox(height: 16),\r\n"
    "            Row(children: [\r\n"
    "              Expanded(\r\n"
    "                child: TextField(\r\n"
    "                  controller: _ctrl,\r\n"
    "                  decoration: InputDecoration(\r\n"
    "                    hintText: T.rw\r\n"
    "                        ? 'Urugero: Ni ikihe gifitiye inyungu gutera?'\r\n"
    "                        : 'e.g. Which crop is most profitable this season?',\r\n"
    "                    border: OutlineInputBorder(\r\n"
    "                        borderRadius: BorderRadius.circular(12)),\r\n"
    "                    contentPadding: const EdgeInsets.symmetric(\r\n"
    "                        horizontal: 14, vertical: 12),\r\n"
    "                  ),\r\n"
    "                  onSubmitted: (_) => _ask(),\r\n"
    "                  textInputAction: TextInputAction.send,\r\n"
    "                ),\r\n"
    "              ),\r\n"
    "              const SizedBox(width: 10),\r\n"
    "              _loading\r\n"
    "                  ? const SizedBox(width: 44, height: 44,\r\n"
    "                      child: CircularProgressIndicator(\r\n"
    "                          color: kSprout, strokeWidth: 3))\r\n"
    "                  : IconButton.filled(\r\n"
    "                      style: IconButton.styleFrom(backgroundColor: kForest),\r\n"
    "                      icon: const Icon(Icons.send, color: Colors.white),\r\n"
    "                      onPressed: _ask,\r\n"
    "                    ),\r\n"
    "            ]),\r\n"
    "            if (_error != null) ...[\r\n"
    "              const SizedBox(height: 14),\r\n"
    "              _ErrorBanner(_error!),\r\n"
    "            ],\r\n"
    "            if (_answer != null) ...[\r\n"
    "              const SizedBox(height: 16),\r\n"
    "              Container(\r\n"
    "                width: double.infinity,\r\n"
    "                padding: const EdgeInsets.all(16),\r\n"
    "                decoration: BoxDecoration(\r\n"
    "                  color: kSprout.withValues(alpha: 0.08),\r\n"
    "                  borderRadius: BorderRadius.circular(14),\r\n"
    "                  border: Border.all(color: kSprout.withValues(alpha: 0.25)),\r\n"
    "                ),\r\n"
    "                child: Column(\r\n"
    "                  crossAxisAlignment: CrossAxisAlignment.start,\r\n"
    "                  children: [\r\n"
    "                    Row(children: [\r\n"
    "                      const Icon(Icons.eco, color: kForest, size: 16),\r\n"
    "                      const SizedBox(width: 6),\r\n"
    "                      Text(T.rw ? 'Igisubizo' : 'AI Response',\r\n"
    "                          style: const TextStyle(fontWeight: FontWeight.w700,\r\n"
    "                              fontSize: 12, color: kForest)),\r\n"
    "                    ]),\r\n"
    "                    const SizedBox(height: 10),\r\n"
    "                    Text(_answer!,\r\n"
    "                        style: const TextStyle(fontSize: 14, height: 1.5)),\r\n"
    "                  ],\r\n"
    "                ),\r\n"
    "              ),\r\n"
    "            ],\r\n"
    "            const SizedBox(height: 10),\r\n"
    "          ],\r\n"
    "        ),\r\n"
    "      ),\r\n"
    "    );\r\n"
    "  }\r\n"
    "}\r\n"
    "\r\n"
)

old = "class _FarmStat extends StatelessWidget {"
if old in content:
    content = content.replace(old, ai_widget + old, 1)
    with open("C:/xampp/htdocs/agri_forecast/agri_mobile/lib/main.dart", "w", encoding="utf-8", newline="") as f:
        f.write(content)
    print("SUCCESS")
else:
    print("FAILED")
