f=open("C:/xampp/htdocs/agri_forecast/agri_mobile/lib/main.dart","r",encoding="utf-8")
c=f.read()
f.close()
idx=c.find("agriforecast-production.up.railway.app")
print("found at:", idx)
print(repr(c[idx-40:idx+60]))
f=open("C:/xampp/htdocs/agri_forecast/agri_mobile/lib/main.dart","w",encoding="utf-8")
f.write(c.replace("agriforecast-production.up.railway.app","69.46.46.118"))
f.close()
print("DONE")
